name: eoya_gaja
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fancy_bar: ^2.0.0
  water_drop_nav_bar: ^2.1.0+4
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.1.0
  google_sign_in: ^5.2.1
  shimmer: ^2.0.0
  flutter_login: ^2.2.1
  flutter_slidable: ^1.2.0
  weather: ^2.0.1
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  date_picker_timeline: ^1.2.3
  easy_localization: ^3.0.0
  top_snackbar_flutter: ^1.0.1
  get: ^4.3.8
  flutter_svg: ^1.0.3
  geolocator: ^7.6.2
  card_swiper: ^1.0.4
  swipeable_tile: ^0.0.2
  flutter_native_splash: ^1.3.1
  image_picker: ^0.8.4+4
  simple_speed_dial: ^0.1.3
  adaptive_action_sheet: ^2.0.0
  dropdown_search: ^2.0.1
  flutter_neat_and_clean_calendar: ^0.2.3+11
  quds_popup_menu: ^0.0.1+1
  like_button: ^2.0.3
  animated_button_bar: ^0.0.2+1
  calendar_appbar: ^0.0.6
  date_time_picker: ^2.1.0
  ej_stepper: ^0.1.0
  im_stepper: ^0.1.3
  argon_buttons_flutter: ^1.1.0
  circular_countdown_timer: ^0.2.0
  stop_watch_timer: ^1.3.1
  google_maps_flutter: ^2.1.1
  sliding_up_panel: ^2.0.0+1
  fl_chart: ^0.40.6
  location: ^4.3.0
  google_fonts: ^2.1.1
  calendar_timeline: ^1.0.4
  audioplayers: ^0.20.1
  cached_network_image: ^3.2.0
  flutter_add_to_cart_button: ^1.0.0+1
  polymaker: ^1.0.2
  flutter_circle_chart: ^1.0.0
  fluttermoji: ^0.2.3
  font_awesome_flutter: ^9.2.0
  confetti: ^0.6.0
  loading_animation_widget: ^1.1.0+0
  flutter_animator: ^3.2.1
  custom_refresh_indicator: ^1.0.0
  connectivity_plus: ^2.2.0
  animated_text_kit: ^4.2.1
  flutter_reaction_button: ^2.0.0+1
  flutter_rating_bar: ^4.0.0
  counter_button: ^1.0.1
  fast_color_picker: ^0.1.1
  dough: ^1.0.0
  flutter_gradient_colors: ^2.1.1
  sqflite: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.9
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/bellsound.mp3
    - assets/gifs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: TmonMonsori
      fonts:
        - asset: assets/fonts/TmonMonsori.ttf
    - family: CeraRound
      fonts:
        - asset: assets/fonts/ceraroundpro-bold.otf
        - asset: assets/fonts/ceraroundpro-black.otf
        - asset: assets/fonts/ceraroundpro-light.otf
        - asset: assets/fonts/ceraroundpro-medium.otf
        - asset: assets/fonts/ceraroundpro-regular.otf
        - asset: assets/fonts/ceraroundpro-thin.otf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
    - family: QuickSand
      fonts:
        - asset: assets/fonts/QuickSand-Bold.ttf
        - asset: assets/fonts/QuickSand-Regular.ttf
        - asset: assets/fonts/QuickSand-Light.ttf
        - asset: assets/fonts/QuickSand-SemiBold.ttf
        - asset: assets/fonts/QuickSand-Medium.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Bold.ttf
        - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
        - asset: assets/fonts/SourceSansPro-ExtraLightItalic.ttf
        - asset: assets/fonts/SourceSansPro-Italic.ttf
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Light.ttf
        - asset: assets/fonts/SourceSansPro-LightItalic.ttf
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
        - asset: assets/fonts/SourceSansPro-SemiBoldItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
